### PR TITLE
Automated build

### LINKED ISSUE #58: Automated build
We should have document such as DEVEL.md that should provide reproducible way to setup up local environment.

It should contain machine prerequisites, along with any procedure required to build the app.

### PR DESCRIPTION
**Pull request by majkinetor**
Closes #58

### CODE REVIEW

**Comment by majkinetor** [comment]
Check out [DEVELOP.md](https://github.com/VShawn/PRemoteM/blob/1fe271d62947979555bd346702bcc9365e8add81/DEVELOP.md) and changed [README.md](https://github.com/VShawn/PRemoteM/blob/d1ed76c5982af04243c49a05d00d0648bda6f455/readme.md)

**Comment by majkinetor** [comment]
Not sure from where AppVeyor jumps in :-)

**Comment by majkinetor** [comment]
BTW, running from the root `./Invoke-Build.ps1 Build` should probably work for you. It will automatically detect msbuild and assume everything else is installed.

**Review by VShawn — APPROVED** [review]
checked

**Pull request merged**
